[2025-08-19T09:16:52.503+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-19T09:16:52.575+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_audit_dag.validate_audit_task manual__2025-08-19T09:05:52.580030+00:00 [queued]>
[2025-08-19T09:16:52.597+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_audit_dag.validate_audit_task manual__2025-08-19T09:05:52.580030+00:00 [queued]>
[2025-08-19T09:16:52.599+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-08-19T09:16:52.631+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): validate_audit_task> on 2025-08-19 09:05:52.580030+00:00
[2025-08-19T09:16:52.658+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2094) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-19T09:16:52.662+0000] {standard_task_runner.py:63} INFO - Started process 2099 to run task
[2025-08-19T09:16:52.662+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_audit_dag', 'validate_audit_task', 'manual__2025-08-19T09:05:52.580030+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/data_audit_dag.py', '--cfg-path', '/tmp/tmprxc9ckut']
[2025-08-19T09:16:52.668+0000] {standard_task_runner.py:91} INFO - Job 24: Subtask validate_audit_task
[2025-08-19T09:16:52.816+0000] {task_command.py:426} INFO - Running <TaskInstance: data_audit_dag.validate_audit_task manual__2025-08-19T09:05:52.580030+00:00 [running]> on host 37fc8edea13d
[2025-08-19T09:16:53.851+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='youremail@example.com' AIRFLOW_CTX_DAG_OWNER='rajpriya' AIRFLOW_CTX_DAG_ID='data_audit_dag' AIRFLOW_CTX_TASK_ID='validate_audit_task' AIRFLOW_CTX_EXECUTION_DATE='2025-08-19T09:05:52.580030+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-19T09:05:52.580030+00:00'
[2025-08-19T09:16:53.867+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-19T09:16:54.448+0000] {logging_mixin.py:188} INFO - [Audit] Validation result saved: {'data': {'user_id': 101, 'balance': 1413, 'timestamp': '2025-08-19 09:06:02.393847'}, 'valid': True}
[2025-08-19T09:16:54.455+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-19T09:16:54.457+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-19T09:16:55.427+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_audit_dag, task_id=validate_audit_task, run_id=manual__2025-08-19T09:05:52.580030+00:00, execution_date=20250819T090552, start_date=20250819T091652, end_date=20250819T091655
[2025-08-19T09:16:55.539+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-19T09:16:55.780+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-19T09:16:55.784+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
