[2025-08-19T09:17:02.721+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-19T09:17:02.796+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_audit_dag.validate_audit_task scheduled__2025-08-19T08:00:00+00:00 [queued]>
[2025-08-19T09:17:02.822+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_audit_dag.validate_audit_task scheduled__2025-08-19T08:00:00+00:00 [queued]>
[2025-08-19T09:17:02.824+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-19T09:17:02.881+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): validate_audit_task> on 2025-08-19 08:00:00+00:00
[2025-08-19T09:17:02.937+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2102) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-19T09:17:02.945+0000] {standard_task_runner.py:63} INFO - Started process 2108 to run task
[2025-08-19T09:17:02.945+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_audit_dag', 'validate_audit_task', 'scheduled__2025-08-19T08:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/data_audit_dag.py', '--cfg-path', '/tmp/tmplk5oehb9']
[2025-08-19T09:17:02.955+0000] {standard_task_runner.py:91} INFO - Job 29: Subtask validate_audit_task
[2025-08-19T09:17:04.618+0000] {task_command.py:426} INFO - Running <TaskInstance: data_audit_dag.validate_audit_task scheduled__2025-08-19T08:00:00+00:00 [running]> on host 37fc8edea13d
[2025-08-19T09:17:14.978+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 29 for task validate_audit_task ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 2108)
[2025-08-19T09:17:28.408+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-19T09:17:28.540+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-19T09:17:28.546+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
