[2025-08-19T10:40:34.483+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-19T10:40:36.415+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_audit_dag.data_pull_task scheduled__2025-08-19T09:00:00+00:00 [queued]>
[2025-08-19T10:40:36.457+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_audit_dag.data_pull_task scheduled__2025-08-19T09:00:00+00:00 [queued]>
[2025-08-19T10:40:36.461+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-19T10:40:36.554+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_pull_task> on 2025-08-19 09:00:00+00:00
[2025-08-19T10:40:36.603+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=704) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-19T10:40:36.609+0000] {standard_task_runner.py:63} INFO - Started process 714 to run task
[2025-08-19T10:40:36.609+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_audit_dag', 'data_pull_task', 'scheduled__2025-08-19T09:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/Assessment_2/data_audit_dag.py', '--cfg-path', '/tmp/tmpq96gwg8s']
[2025-08-19T10:40:36.642+0000] {standard_task_runner.py:91} INFO - Job 48: Subtask data_pull_task
[2025-08-19T10:40:37.020+0000] {task_command.py:426} INFO - Running <TaskInstance: data_audit_dag.data_pull_task scheduled__2025-08-19T09:00:00+00:00 [running]> on host 37fc8edea13d
[2025-08-19T10:40:37.331+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='youremail@example.com' AIRFLOW_CTX_DAG_OWNER='rajpriya' AIRFLOW_CTX_DAG_ID='data_audit_dag' AIRFLOW_CTX_TASK_ID='data_pull_task' AIRFLOW_CTX_EXECUTION_DATE='2025-08-19T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-19T09:00:00+00:00'
[2025-08-19T10:40:37.358+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-19T10:40:37.381+0000] {logging_mixin.py:188} INFO - [Pull] Pulled Data: {'user_id': 101, 'balance': 1247, 'timestamp': '2025-08-19 10:40:37.377351'}
[2025-08-19T10:40:37.383+0000] {python.py:237} INFO - Done. Returned value was: {'user_id': 101, 'balance': 1247, 'timestamp': '2025-08-19 10:40:37.377351'}
[2025-08-19T10:40:37.386+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-19T10:40:37.490+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_audit_dag, task_id=data_pull_task, run_id=scheduled__2025-08-19T09:00:00+00:00, execution_date=20250819T090000, start_date=20250819T104036, end_date=20250819T104037
[2025-08-19T10:40:37.575+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-19T10:40:37.647+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-19T10:40:37.652+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
